# Changes here will be overwritten by Copier
_commit: 2.6.0
_src_path: gh:DiamondLightSource/python-copier-template
author_email: callum.forrester@diamond.ac.uk
author_name: Callum Forrester
component_lifecycle: experimental
component_owner: group:default/daq
component_type: library
description: Bluesky playground environment for Diamond's htss rigs
distribution_name: htss-rig-bluesky
docker: true
docs_type: sphinx
git_platform: github.com
github_org: DiamondLightSource
package_name: htss_rig_bluesky
pypi: true
repo_name: htss-rig-bluesky
type_checker: mypy
